"""fix model user_tg changed user_tg_id

Revision ID: c2f72ef31a99
Revises: 2d485c3cb789
Create Date: 2025-12-19 17:24:41.654804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2f72ef31a99'
down_revision: Union[str, Sequence[str], None] = '2d485c3cb789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
